---
- name: install dependency
  hosts: web
  become: true

  tasks:
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: yes

    - name: start and enable nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

    - name: copy the file
      ansible.builtin.copy:
        src: ../files/index.html
        dest: /var/www/html/index.html

    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted